name: Continuos Integration

on: 
  pull_request:
    branches:
      ["master"]

jobs:
  continuos_integration:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
        flutter-version: 3.30.x
    - run: flutter --version
    - run: cd fundamentos_plus_mobile
    - run: flutter pub get
    - run: flutter test --coverage
